NDefines.NGame.START_DATE = "1967.1.1.1"
NDefines.NGame.END_DATE = "1980.12.31.1"

NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 4;
NDefines.NDiplomacy.VOLUNTEERS_PER_TARGET_PROVINCE = 1.0;
NDefines.NDiplomacy.OPINION_PER_VOLUNTEER = 2;
