NDefines.NGame.START_DATE = "1967.1.1.1"
NDefines.NGame.END_DATE = "1980.12.31.1"

NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 4;
NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 1;
NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION  = 0.1;
NDefines.NDiplomacy.VOLUNTEERS_PER_TARGET_PROVINCE = 1.0;
NDefines.NCountry.AIR_VOLUNTEER_PLANES_LIMIT = 2;
NDefines.NCountry.AIR_VOLUNTEER_BASES_CAPACITY_LIMIT = 1;
